version: "3.9"
services:
  app:
    image: rubyapp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:alpine3.17
    environment:
      POSTGRES_PASSWORD: password
